# Generated by Django 6.0.7 on 2026-08-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referrer_id',
            new_name='referrer',
        ),
    ]
