# Generated by Django 6.0.7 on 2026-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_referrer_id_user_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('operator', 'Operator')], default='user'),
        ),
    ]
