# Generated by Django 6.0.7 on 2026-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('operator', 'Operator'), ('driver', 'Haydovchi')], default='user'),
        ),
    ]
