# Generated by Django 6.0.7 on 2026-08-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.district'),
        ),
    ]
