# Generated by Django 6.0.7 on 2026-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
