# Generated by Django 6.0.7 on 2026-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visited',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
