# Generated by Django 6.0.7 on 2026-08-12 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_thread'),
        ('orders', '0005_order_visited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('packaging', 'Qadoqlash'), ('shipping', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('pickup_later', 'Keyin oladi'), ('returned', 'Qaytib keldi'), ('cancelled', 'Bekor qilindi'), ('hold', 'Hold'), ('archive', 'Arxiv')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
