# Generated by Django 6.0.7 on 2026-08-15 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='thread',
        ),
        migrations.AlterField(
            model_name='survey',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='orders.order'),
        ),
    ]
