# Generated by Django 6.0.7 on 2026-08-20 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_user_role'),
        ('orders', '0009_order_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.district'),
        ),
    ]
