# Generated by Django 6.0.7 on 2026-08-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_payment_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
