# Generated by Django 6.0.7 on 2026-08-22 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_delivered_at_order_driver_order_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?998\\d{9}$', "Telefon raqami noto'g'ri formatda. Masalan: +998 90 123 45 67")]),
        ),
    ]
