# Generated by Django 6.0.7 on 2026-08-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='visited',
        ),
    ]
