# Generated by Django 6.0.7 on 2026-08-23 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
        ('catalog', '0003_thread_visit_count'),
        ('orders', '0018_remove_order_visited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'operator'], name='orders_orde_status_47ca16_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'driver'], name='orders_orde_status_b91e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver', 'status'], name='orders_orde_driver__83706f_idx'),
        ),
    ]
