# Generated by Django 6.0.7 on 2026-08-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_b91e8b_idx',
        ),
    ]
